version: '3.7'

services:
  django:
    container_name: four_a
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/four_rest/manage.py migrate --noinput &&
             python /usr/src/four_rest/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/four_rest
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # expose:
    #   - "5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    #   POSTGRES_DB: "db"
    #   POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  postgres_data: