version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn fourArest.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    # ports:
    #   - 8000:8000
    # файл с настройками для dev разработки
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  vue:
    build:
      context: ./vue-four-a
      dockerfile: Dockerfile.prod
    volumes:
      - vue_dist:/app/dist
    depends_on:
      - web
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - vue_dist:/app/dist
    depends_on:
      - web
      - vue
volumes:
  postgres_data:
  static_volume:
  vue_dist: